spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: program
    password: test
    url: jdbc:postgresql://localhost:5432/persons

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
