name: GitHub Actions
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run API Tests
          uses: matt-ball/newman-action@v1.0.4
          with:
            collection: postman/[inst] Lab1.postman_collection.json
            environment: postman/[inst][heroku] Lab1.postman_environment.json
            delayRequest: 100
            reporters: '[ "cli" ]'

#help
#praise the Ilyas
